experiments:
  - size: L
    replaced_non_terminal: NP
    num_generated_sentences: 5
    augmentation: GR
    random_seed: 52
    time: 01:00:00

  - size: L
    replaced_non_terminal: NP
    num_generated_sentences: 5
    augmentation: GR
    random_seed: 152
    time: 01:00:00

  - size: L
    replaced_non_terminal: NP
    num_generated_sentences: 5
    augmentation: GR
    random_seed: 300
    time: 01:00:00

  - size: L
    replaced_non_terminal: NP
    num_generated_sentences: 5
    augmentation: GR
    random_seed: 30
    time: 01:00:00

  - size: L
    replaced_non_terminal: NP
    num_generated_sentences: 5
    augmentation: GR
    random_seed: 900
    time: 01:00:00

  - size: L
    replaced_non_terminal: NP
    num_generated_sentences: 10
    augmentation: GR
    random_seed: 52
    time: 01:00:00

  - size: L
    replaced_non_terminal: NP
    num_generated_sentences: 10
    augmentation: GR
    random_seed: 152
    time: 01:00:00

  - size: L
    replaced_non_terminal: NP
    num_generated_sentences: 10
    augmentation: GR
    random_seed: 300
    time: 01:00:00

  - size: L
    replaced_non_terminal: NP
    num_generated_sentences: 10
    augmentation: GR
    random_seed: 30
    time: 01:00:00

  - size: L
    replaced_non_terminal: NP
    num_generated_sentences: 10
    augmentation: GR
    random_seed: 900
    time: 01:00:00

  - size: L
    replaced_non_terminal: VP
    num_generated_sentences: 5
    augmentation: GR
    random_seed: 52
    time: 01:00:00

  - size: L
    replaced_non_terminal: VP
    num_generated_sentences: 5
    augmentation: GR
    random_seed: 152
    time: 01:00:00

  - size: L
    replaced_non_terminal: VP
    num_generated_sentences: 5
    augmentation: GR
    random_seed: 300
    time: 01:00:00

  - size: L
    replaced_non_terminal: VP
    num_generated_sentences: 5
    augmentation: GR
    random_seed: 30
    time: 01:00:00

  - size: L
    replaced_non_terminal: VP
    num_generated_sentences: 5
    augmentation: GR
    random_seed: 900
    time: 01:00:00

  - size: L
    replaced_non_terminal: VP
    num_generated_sentences: 10
    augmentation: GR
    random_seed: 52
    time: 01:00:00

  - size: L
    replaced_non_terminal: VP
    num_generated_sentences: 10
    augmentation: GR
    random_seed: 152
    time: 01:00:00

  - size: L
    replaced_non_terminal: VP
    num_generated_sentences: 10
    augmentation: GR
    random_seed: 300
    time: 01:00:00

  - size: L
    replaced_non_terminal: VP
    num_generated_sentences: 10
    augmentation: GR
    random_seed: 30
    time: 01:00:00

  - size: L
    replaced_non_terminal: VP
    num_generated_sentences: 10
    augmentation: GR
    random_seed: 900
    time: 01:00:00