experiments:
  - size: S
    pretrained_dir: ariesutiono/scibert-lm-const-finetuned-20
    replaced_non_terminal: XP
    num_generated_sentences:
      - 1
      - 10
      - 20
    augmentation: LM
    n_replace_non_terminals:
      - 5
      - 3
      - 5
    random_seeds:
      - 52
      - 152
      - 300
      - 30
      - 900
    time: 02:00:00

  - size: M
    pretrained_dir: ariesutiono/scibert-lm-const-finetuned-20
    replaced_non_terminal: XP
    num_generated_sentences:
      - 5
      - 10
      - 20
    augmentation: LM
    n_replace_non_terminals:
      - 1
      - 3
      - 5
    random_seeds:
      - 52
      - 152
      - 300
      - 30
      - 900
    time: 04:30:00

  - size: L
    pretrained_dir: ariesutiono/scibert-lm-const-finetuned-20
    replaced_non_terminal: XP
    num_generated_sentences:
      - 5
      - 10
      - 20
    augmentation: LM
    n_replace_non_terminals:
      - 1
      - 3
      - 5
    random_seeds:
      - 52
      - 152
      - 300
      - 30
      - 900
    time: 07:30:00