experiments:
  - size: S
    replaced_non_terminal: XP
    num_generated_sentences:
      - 1
      - 10
      - 20
    augmentation: LM
    n_replace_non_terminals:
      - 5
      - 3
      - 5
    random_seeds:
      - 52
      - 152
      - 300
      - 30
      - 900
    time: 01:00:00

  - size: M
    replaced_non_terminal: XP
    num_generated_sentences:
      - 5
      - 10
      - 20
    augmentation: LM
    n_replace_non_terminals:
      - 1
      - 3
      - 5
    random_seeds:
      - 52
      - 152
      - 300
      - 30
      - 900
    time: 02:30:00

  - size: L
    replaced_non_terminal: XP
    num_generated_sentences:
      - 5
      - 10
      - 20
    augmentation: LM
    n_replace_non_terminals:
      - 1
      - 3
      - 5
    random_seeds:
      - 52
      - 152
      - 300
      - 30
      - 900
    time: 05:30:00