experiments:
  - size: M
    replaced_non_terminal: NP
    num_generated_sentences: 10
    augmentation: GR
    random_seed: 52

  - size: M
    replaced_non_terminal: NP
    num_generated_sentences: 10
    augmentation: GR
    random_seed: 152

  - size: M
    replaced_non_terminal: NP
    num_generated_sentences: 10
    augmentation: GR
    random_seed: 300

  - size: M
    replaced_non_terminal: NP
    num_generated_sentences: 10
    augmentation: GR
    random_seed: 30

  - size: M
    replaced_non_terminal: NP
    num_generated_sentences: 10
    augmentation: GR
    random_seed: 900
