experiments:
  - size: S
    replaced_non_terminal: NP
    num_generated_sentences: 5
    augmentation: SYN
    random_seed: 52

  - size: S
    replaced_non_terminal: NP
    num_generated_sentences: 5
    augmentation: SYN
    random_seed: 152

  - size: S
    replaced_non_terminal: NP
    num_generated_sentences: 5
    augmentation: SYN
    random_seed: 300

  - size: S
    replaced_non_terminal: NP
    num_generated_sentences: 5
    augmentation: SYN
    random_seed: 30

  - size: S
    replaced_non_terminal: NP
    num_generated_sentences: 5
    augmentation: SYN
    random_seed: 900

  - size: M
    replaced_non_terminal: NP
    num_generated_sentences: 5
    augmentation: SYN
    random_seed: 52

  - size: M
    replaced_non_terminal: NP
    num_generated_sentences: 5
    augmentation: SYN
    random_seed: 152

  - size: M
    replaced_non_terminal: NP
    num_generated_sentences: 5
    augmentation: SYN
    random_seed: 300

  - size: M
    replaced_non_terminal: NP
    num_generated_sentences: 5
    augmentation: SYN
    random_seed: 30

  - size: M
    replaced_non_terminal: NP
    num_generated_sentences: 5
    augmentation: SYN
    random_seed: 900

  - size: L
    replaced_non_terminal: NP
    num_generated_sentences: 5
    augmentation: SYN
    random_seed: 52

  - size: L
    replaced_non_terminal: NP
    num_generated_sentences: 5
    augmentation: SYN
    random_seed: 152

  - size: L
    replaced_non_terminal: NP
    num_generated_sentences: 5
    augmentation: SYN
    random_seed: 300

  - size: L
    replaced_non_terminal: NP
    num_generated_sentences: 5
    augmentation: SYN
    random_seed: 30

  - size: L
    replaced_non_terminal: NP
    num_generated_sentences: 5
    augmentation: SYN
    random_seed: 900